# These go on units to denote their method of locomotion
MOVE_FOOT  = 0x1
MOVE_HORSE = 0x2
MOVE_FLY   = 0x4
MOVE_MECHA = 0x8

# These go on tiles
NONE_IMPASS  = 0x0
FOOT_IMPASS  = 0x1
HORSE_IMPASS = 0x2
FLY_IMPASS   = 0x4
MECHA_IMPASS = 0x8
FOOT_SLOW    = 0x10
HORSE_SLOW   = 0x20
FLY_SLOW     = 0x40
MECHA_SLOW   = 0x80
GROUND_SLOW =  FOOT_SLOW | HORSE_SLOW | MECHA_SLOW
GROUND_IMPASS = FOOT_IMPASS | HORSE_IMPASS | MECHA_IMPASS
IMPASS = FOOT_IMPASS | HORSE_IMPASS | FLY_IMPASS | MECHA_IMPASS